// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package network_acl

import (
	"context"
	"errors"
	"fmt"
	"reflect"
	"strings"

	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	ackcondition "github.com/aws-controllers-k8s/runtime/pkg/condition"
	ackerr "github.com/aws-controllers-k8s/runtime/pkg/errors"
	ackrequeue "github.com/aws-controllers-k8s/runtime/pkg/requeue"
	ackrtlog "github.com/aws-controllers-k8s/runtime/pkg/runtime/log"
	"github.com/aws/aws-sdk-go/aws"
	svcsdk "github.com/aws/aws-sdk-go/service/ec2"
	corev1 "k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	svcapitypes "github.com/aws-controllers-k8s/ec2-controller/apis/v1alpha1"
)

// Hack to avoid import errors during build...
var (
	_ = &metav1.Time{}
	_ = strings.ToLower("")
	_ = &aws.JSONValue{}
	_ = &svcsdk.EC2{}
	_ = &svcapitypes.NetworkACL{}
	_ = ackv1alpha1.AWSAccountID("")
	_ = &ackerr.NotFound
	_ = &ackcondition.NotManagedMessage
	_ = &reflect.Value{}
	_ = fmt.Sprintf("")
	_ = &ackrequeue.NoRequeue{}
)

// sdkFind returns SDK-specific information about a supplied resource
func (rm *resourceManager) sdkFind(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkFind")
	defer func() {
		exit(err)
	}()
	// If any required fields in the input shape are missing, AWS resource is
	// not created yet. Return NotFound here to indicate to callers that the
	// resource isn't yet created.
	if rm.requiredFieldsMissingFromReadManyInput(r) {
		return nil, ackerr.NotFound
	}

	input, err := rm.newListRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DescribeNetworkAclsOutput
	resp, err = rm.sdkapi.DescribeNetworkAclsWithContext(ctx, input)
	rm.metrics.RecordAPICall("READ_MANY", "DescribeNetworkAcls", err)
	if err != nil {
		if awsErr, ok := ackerr.AWSError(err); ok && awsErr.Code() == "InvalidVpcID.NotFound" {
			return nil, ackerr.NotFound
		}
		return nil, err
	}

	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := r.ko.DeepCopy()

	found := false
	for _, elem := range resp.NetworkAcls {
		if elem.Associations != nil {
			f0 := []*svcapitypes.NetworkACLAssociation{}
			for _, f0iter := range elem.Associations {
				f0elem := &svcapitypes.NetworkACLAssociation{}
				if f0iter.NetworkAclAssociationId != nil {
					f0elem.NetworkACLAssociationID = f0iter.NetworkAclAssociationId
				}
				if f0iter.NetworkAclId != nil {
					f0elem.NetworkACLID = f0iter.NetworkAclId
				}
				if f0iter.SubnetId != nil {
					f0elem.SubnetID = f0iter.SubnetId
				}
				f0 = append(f0, f0elem)
			}
			ko.Status.Associations = f0
		} else {
			ko.Status.Associations = nil
		}
		if elem.Entries != nil {
			f1 := []*svcapitypes.NetworkACLEntry{}
			for _, f1iter := range elem.Entries {
				f1elem := &svcapitypes.NetworkACLEntry{}
				if f1iter.CidrBlock != nil {
					f1elem.CIDRBlock = f1iter.CidrBlock
				}
				if f1iter.Egress != nil {
					f1elem.Egress = f1iter.Egress
				}
				if f1iter.IcmpTypeCode != nil {
					f1elemf2 := &svcapitypes.ICMPTypeCode{}
					if f1iter.IcmpTypeCode.Code != nil {
						f1elemf2.Code = f1iter.IcmpTypeCode.Code
					}
					if f1iter.IcmpTypeCode.Type != nil {
						f1elemf2.Type = f1iter.IcmpTypeCode.Type
					}
					f1elem.ICMPTypeCode = f1elemf2
				}
				if f1iter.Ipv6CidrBlock != nil {
					f1elem.IPv6CIDRBlock = f1iter.Ipv6CidrBlock
				}
				if f1iter.PortRange != nil {
					f1elemf4 := &svcapitypes.PortRange{}
					if f1iter.PortRange.From != nil {
						f1elemf4.From = f1iter.PortRange.From
					}
					if f1iter.PortRange.To != nil {
						f1elemf4.To = f1iter.PortRange.To
					}
					f1elem.PortRange = f1elemf4
				}
				if f1iter.Protocol != nil {
					f1elem.Protocol = f1iter.Protocol
				}
				if f1iter.RuleAction != nil {
					f1elem.RuleAction = f1iter.RuleAction
				}
				if f1iter.RuleNumber != nil {
					f1elem.RuleNumber = f1iter.RuleNumber
				}
				f1 = append(f1, f1elem)
			}
			ko.Status.Entries = f1
		} else {
			ko.Status.Entries = nil
		}
		if elem.IsDefault != nil {
			ko.Status.IsDefault = elem.IsDefault
		} else {
			ko.Status.IsDefault = nil
		}
		if elem.NetworkAclId != nil {
			ko.Status.NetworkACLID = elem.NetworkAclId
		} else {
			ko.Status.NetworkACLID = nil
		}
		if elem.OwnerId != nil {
			ko.Status.OwnerID = elem.OwnerId
		} else {
			ko.Status.OwnerID = nil
		}
		if elem.Tags != nil {
			f5 := []*svcapitypes.Tag{}
			for _, f5iter := range elem.Tags {
				f5elem := &svcapitypes.Tag{}
				if f5iter.Key != nil {
					f5elem.Key = f5iter.Key
				}
				if f5iter.Value != nil {
					f5elem.Value = f5iter.Value
				}
				f5 = append(f5, f5elem)
			}
			ko.Spec.Tags = f5
		} else {
			ko.Spec.Tags = nil
		}
		if elem.VpcId != nil {
			ko.Spec.VPCID = elem.VpcId
		} else {
			ko.Spec.VPCID = nil
		}
		found = true
		break
	}
	if !found {
		return nil, ackerr.NotFound
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// requiredFieldsMissingFromReadManyInput returns true if there are any fields
// for the ReadMany Input shape that are required but not present in the
// resource's Spec or Status
func (rm *resourceManager) requiredFieldsMissingFromReadManyInput(
	r *resource,
) bool {
	return r.ko.Status.NetworkACLID == nil

}

// newListRequestPayload returns SDK-specific struct for the HTTP request
// payload of the List API call for the resource
func (rm *resourceManager) newListRequestPayload(
	r *resource,
) (*svcsdk.DescribeNetworkAclsInput, error) {
	res := &svcsdk.DescribeNetworkAclsInput{}

	if r.ko.Status.NetworkACLID != nil {
		f3 := []*string{}
		f3 = append(f3, r.ko.Status.NetworkACLID)
		res.SetNetworkAclIds(f3)
	}

	return res, nil
}

// sdkCreate creates the supplied resource in the backend AWS service API and
// returns a copy of the resource with resource fields (in both Spec and
// Status) filled in with values from the CREATE API operation's Output shape.
func (rm *resourceManager) sdkCreate(
	ctx context.Context,
	desired *resource,
) (created *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkCreate")
	defer func() {
		exit(err)
	}()
	input, err := rm.newCreateRequestPayload(ctx, desired)
	if err != nil {
		return nil, err
	}
	updateTagSpecificationsInCreateRequest(desired, input)

	var resp *svcsdk.CreateNetworkAclOutput
	_ = resp
	resp, err = rm.sdkapi.CreateNetworkAclWithContext(ctx, input)
	rm.metrics.RecordAPICall("CREATE", "CreateNetworkAcl", err)
	if err != nil {
		return nil, err
	}
	// Merge in the information we read from the API call above to the copy of
	// the original Kubernetes object we passed to the function
	ko := desired.ko.DeepCopy()

	if resp.NetworkAcl.Associations != nil {
		f0 := []*svcapitypes.NetworkACLAssociation{}
		for _, f0iter := range resp.NetworkAcl.Associations {
			f0elem := &svcapitypes.NetworkACLAssociation{}
			if f0iter.NetworkAclAssociationId != nil {
				f0elem.NetworkACLAssociationID = f0iter.NetworkAclAssociationId
			}
			if f0iter.NetworkAclId != nil {
				f0elem.NetworkACLID = f0iter.NetworkAclId
			}
			if f0iter.SubnetId != nil {
				f0elem.SubnetID = f0iter.SubnetId
			}
			f0 = append(f0, f0elem)
		}
		ko.Status.Associations = f0
	} else {
		ko.Status.Associations = nil
	}
	if resp.NetworkAcl.Entries != nil {
		f1 := []*svcapitypes.NetworkACLEntry{}
		for _, f1iter := range resp.NetworkAcl.Entries {
			f1elem := &svcapitypes.NetworkACLEntry{}
			if f1iter.CidrBlock != nil {
				f1elem.CIDRBlock = f1iter.CidrBlock
			}
			if f1iter.Egress != nil {
				f1elem.Egress = f1iter.Egress
			}
			if f1iter.IcmpTypeCode != nil {
				f1elemf2 := &svcapitypes.ICMPTypeCode{}
				if f1iter.IcmpTypeCode.Code != nil {
					f1elemf2.Code = f1iter.IcmpTypeCode.Code
				}
				if f1iter.IcmpTypeCode.Type != nil {
					f1elemf2.Type = f1iter.IcmpTypeCode.Type
				}
				f1elem.ICMPTypeCode = f1elemf2
			}
			if f1iter.Ipv6CidrBlock != nil {
				f1elem.IPv6CIDRBlock = f1iter.Ipv6CidrBlock
			}
			if f1iter.PortRange != nil {
				f1elemf4 := &svcapitypes.PortRange{}
				if f1iter.PortRange.From != nil {
					f1elemf4.From = f1iter.PortRange.From
				}
				if f1iter.PortRange.To != nil {
					f1elemf4.To = f1iter.PortRange.To
				}
				f1elem.PortRange = f1elemf4
			}
			if f1iter.Protocol != nil {
				f1elem.Protocol = f1iter.Protocol
			}
			if f1iter.RuleAction != nil {
				f1elem.RuleAction = f1iter.RuleAction
			}
			if f1iter.RuleNumber != nil {
				f1elem.RuleNumber = f1iter.RuleNumber
			}
			f1 = append(f1, f1elem)
		}
		ko.Status.Entries = f1
	} else {
		ko.Status.Entries = nil
	}
	if resp.NetworkAcl.IsDefault != nil {
		ko.Status.IsDefault = resp.NetworkAcl.IsDefault
	} else {
		ko.Status.IsDefault = nil
	}
	if resp.NetworkAcl.NetworkAclId != nil {
		ko.Status.NetworkACLID = resp.NetworkAcl.NetworkAclId
	} else {
		ko.Status.NetworkACLID = nil
	}
	if resp.NetworkAcl.OwnerId != nil {
		ko.Status.OwnerID = resp.NetworkAcl.OwnerId
	} else {
		ko.Status.OwnerID = nil
	}
	if resp.NetworkAcl.Tags != nil {
		f5 := []*svcapitypes.Tag{}
		for _, f5iter := range resp.NetworkAcl.Tags {
			f5elem := &svcapitypes.Tag{}
			if f5iter.Key != nil {
				f5elem.Key = f5iter.Key
			}
			if f5iter.Value != nil {
				f5elem.Value = f5iter.Value
			}
			f5 = append(f5, f5elem)
		}
		ko.Spec.Tags = f5
	} else {
		ko.Spec.Tags = nil
	}
	if resp.NetworkAcl.VpcId != nil {
		ko.Spec.VPCID = resp.NetworkAcl.VpcId
	} else {
		ko.Spec.VPCID = nil
	}

	rm.setStatusDefaults(ko)
	return &resource{ko}, nil
}

// newCreateRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Create API call for the resource
func (rm *resourceManager) newCreateRequestPayload(
	ctx context.Context,
	r *resource,
) (*svcsdk.CreateNetworkAclInput, error) {
	res := &svcsdk.CreateNetworkAclInput{}

	if r.ko.Spec.VPCID != nil {
		res.SetVpcId(*r.ko.Spec.VPCID)
	}

	return res, nil
}

// sdkUpdate patches the supplied resource in the backend AWS service API and
// returns a new resource with updated fields.
func (rm *resourceManager) sdkUpdate(
	ctx context.Context,
	desired *resource,
	latest *resource,
	delta *ackcompare.Delta,
) (*resource, error) {
	return rm.customUpdateNetworkAcl(ctx, desired, latest, delta)
}

// sdkDelete deletes the supplied resource in the backend AWS service API
func (rm *resourceManager) sdkDelete(
	ctx context.Context,
	r *resource,
) (latest *resource, err error) {
	rlog := ackrtlog.FromContext(ctx)
	exit := rlog.Trace("rm.sdkDelete")
	defer func() {
		exit(err)
	}()
	input, err := rm.newDeleteRequestPayload(r)
	if err != nil {
		return nil, err
	}
	var resp *svcsdk.DeleteNetworkAclOutput
	_ = resp
	resp, err = rm.sdkapi.DeleteNetworkAclWithContext(ctx, input)
	rm.metrics.RecordAPICall("DELETE", "DeleteNetworkAcl", err)
	return nil, err
}

// newDeleteRequestPayload returns an SDK-specific struct for the HTTP request
// payload of the Delete API call for the resource
func (rm *resourceManager) newDeleteRequestPayload(
	r *resource,
) (*svcsdk.DeleteNetworkAclInput, error) {
	res := &svcsdk.DeleteNetworkAclInput{}

	if r.ko.Status.NetworkACLID != nil {
		res.SetNetworkAclId(*r.ko.Status.NetworkACLID)
	}

	return res, nil
}

// setStatusDefaults sets default properties into supplied custom resource
func (rm *resourceManager) setStatusDefaults(
	ko *svcapitypes.NetworkACL,
) {
	if ko.Status.ACKResourceMetadata == nil {
		ko.Status.ACKResourceMetadata = &ackv1alpha1.ResourceMetadata{}
	}
	if ko.Status.ACKResourceMetadata.Region == nil {
		ko.Status.ACKResourceMetadata.Region = &rm.awsRegion
	}
	if ko.Status.ACKResourceMetadata.OwnerAccountID == nil {
		ko.Status.ACKResourceMetadata.OwnerAccountID = &rm.awsAccountID
	}
	if ko.Status.Conditions == nil {
		ko.Status.Conditions = []*ackv1alpha1.Condition{}
	}
}

// updateConditions returns updated resource, true; if conditions were updated
// else it returns nil, false
func (rm *resourceManager) updateConditions(
	r *resource,
	onSuccess bool,
	err error,
) (*resource, bool) {
	ko := r.ko.DeepCopy()
	rm.setStatusDefaults(ko)

	// Terminal condition
	var terminalCondition *ackv1alpha1.Condition = nil
	var recoverableCondition *ackv1alpha1.Condition = nil
	var syncCondition *ackv1alpha1.Condition = nil
	for _, condition := range ko.Status.Conditions {
		if condition.Type == ackv1alpha1.ConditionTypeTerminal {
			terminalCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeRecoverable {
			recoverableCondition = condition
		}
		if condition.Type == ackv1alpha1.ConditionTypeResourceSynced {
			syncCondition = condition
		}
	}
	var termError *ackerr.TerminalError
	if rm.terminalAWSError(err) || err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
		if terminalCondition == nil {
			terminalCondition = &ackv1alpha1.Condition{
				Type: ackv1alpha1.ConditionTypeTerminal,
			}
			ko.Status.Conditions = append(ko.Status.Conditions, terminalCondition)
		}
		var errorMessage = ""
		if err == ackerr.SecretTypeNotSupported || err == ackerr.SecretNotFound || errors.As(err, &termError) {
			errorMessage = err.Error()
		} else {
			awsErr, _ := ackerr.AWSError(err)
			errorMessage = awsErr.Error()
		}
		terminalCondition.Status = corev1.ConditionTrue
		terminalCondition.Message = &errorMessage
	} else {
		// Clear the terminal condition if no longer present
		if terminalCondition != nil {
			terminalCondition.Status = corev1.ConditionFalse
			terminalCondition.Message = nil
		}
		// Handling Recoverable Conditions
		if err != nil {
			if recoverableCondition == nil {
				// Add a new Condition containing a non-terminal error
				recoverableCondition = &ackv1alpha1.Condition{
					Type: ackv1alpha1.ConditionTypeRecoverable,
				}
				ko.Status.Conditions = append(ko.Status.Conditions, recoverableCondition)
			}
			recoverableCondition.Status = corev1.ConditionTrue
			awsErr, _ := ackerr.AWSError(err)
			errorMessage := err.Error()
			if awsErr != nil {
				errorMessage = awsErr.Error()
			}
			recoverableCondition.Message = &errorMessage
		} else if recoverableCondition != nil {
			recoverableCondition.Status = corev1.ConditionFalse
			recoverableCondition.Message = nil
		}
	}
	// Required to avoid the "declared but not used" error in the default case
	_ = syncCondition
	if terminalCondition != nil || recoverableCondition != nil || syncCondition != nil {
		return &resource{ko}, true // updated
	}
	return nil, false // not updated
}

// terminalAWSError returns awserr, true; if the supplied error is an aws Error type
// and if the exception indicates that it is a Terminal exception
// 'Terminal' exception are specified in generator configuration
func (rm *resourceManager) terminalAWSError(err error) bool {
	// No terminal_errors specified for this resource in generator config
	return false
}

func (rm *resourceManager) newTag(
	c svcapitypes.Tag,
) *svcsdk.Tag {
	res := &svcsdk.Tag{}
	if c.Key != nil {
		res.SetKey(*c.Key)
	}
	if c.Value != nil {
		res.SetValue(*c.Value)
	}

	return res
}
