// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package local_gateway_route_table

import (
	"bytes"
	"reflect"

	ackcompare "github.com/aws-controllers-k8s/runtime/pkg/compare"
	acktags "github.com/aws-controllers-k8s/runtime/pkg/tags"
)

// Hack to avoid import errors during build...
var (
	_ = &bytes.Buffer{}
	_ = &reflect.Method{}
	_ = &acktags.Tags{}
)

// newResourceDelta returns a new `ackcompare.Delta` used to compare two
// resources
func newResourceDelta(
	a *resource,
	b *resource,
) *ackcompare.Delta {
	delta := ackcompare.NewDelta()
	if (a == nil && b != nil) ||
		(a != nil && b == nil) {
		delta.Add("", a, b)
		return delta
	}

	if ackcompare.HasNilDifference(a.ko.Spec.DryRun, b.ko.Spec.DryRun) {
		delta.Add("Spec.DryRun", a.ko.Spec.DryRun, b.ko.Spec.DryRun)
	} else if a.ko.Spec.DryRun != nil && b.ko.Spec.DryRun != nil {
		if *a.ko.Spec.DryRun != *b.ko.Spec.DryRun {
			delta.Add("Spec.DryRun", a.ko.Spec.DryRun, b.ko.Spec.DryRun)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.LocalGatewayID, b.ko.Spec.LocalGatewayID) {
		delta.Add("Spec.LocalGatewayID", a.ko.Spec.LocalGatewayID, b.ko.Spec.LocalGatewayID)
	} else if a.ko.Spec.LocalGatewayID != nil && b.ko.Spec.LocalGatewayID != nil {
		if *a.ko.Spec.LocalGatewayID != *b.ko.Spec.LocalGatewayID {
			delta.Add("Spec.LocalGatewayID", a.ko.Spec.LocalGatewayID, b.ko.Spec.LocalGatewayID)
		}
	}
	if ackcompare.HasNilDifference(a.ko.Spec.Mode, b.ko.Spec.Mode) {
		delta.Add("Spec.Mode", a.ko.Spec.Mode, b.ko.Spec.Mode)
	} else if a.ko.Spec.Mode != nil && b.ko.Spec.Mode != nil {
		if *a.ko.Spec.Mode != *b.ko.Spec.Mode {
			delta.Add("Spec.Mode", a.ko.Spec.Mode, b.ko.Spec.Mode)
		}
	}
	if len(a.ko.Spec.TagSpecifications) != len(b.ko.Spec.TagSpecifications) {
		delta.Add("Spec.TagSpecifications", a.ko.Spec.TagSpecifications, b.ko.Spec.TagSpecifications)
	} else if len(a.ko.Spec.TagSpecifications) > 0 {
		if !reflect.DeepEqual(a.ko.Spec.TagSpecifications, b.ko.Spec.TagSpecifications) {
			delta.Add("Spec.TagSpecifications", a.ko.Spec.TagSpecifications, b.ko.Spec.TagSpecifications)
		}
	}

	return delta
}
