---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ec2-leader-election-role
  namespace: ack-system
rules:
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
