---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: ack-ec2-reader
  namespace: default
rules:
- apiGroups:
  - ec2.services.k8s.aws
  resources:
  - subnets
  - vpcs
  verbs:
  - get
  - list
  - watch
