// Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License"). You may
// not use this file except in compliance with the License. A copy of the
// License is located at
//
//     http://aws.amazon.com/apache2.0/
//
// or in the "license" file accompanying this file. This file is distributed
// on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
// express or implied. See the License for the specific language governing
// permissions and limitations under the License.

// Code generated by ack-generate. DO NOT EDIT.

package v1alpha1

import (
	ackv1alpha1 "github.com/aws-controllers-k8s/runtime/apis/core/v1alpha1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// TransitGatewaySpec defines the desired state of TransitGateway.
//
// Describes a transit gateway.
type TransitGatewaySpec struct {

// A description of the transit gateway.
Description *string `json:"description,omitempty"`
// The transit gateway options.
Options *TransitGatewayRequestOptions `json:"options,omitempty"`
// The tags. The value parameter is required, but if you don't want the tag
// to have a value, specify the parameter with no value, and we set the value
// to an empty string.
Tags []*Tag `json:"tags,omitempty"`
}

// TransitGatewayStatus defines the observed state of TransitGateway
type TransitGatewayStatus struct {
	// All CRs managed by ACK have a common `Status.ACKResourceMetadata` member
	// that is used to contain resource sync state, account ownership,
	// constructed ARN for the resource
	// +kubebuilder:validation:Optional
	ACKResourceMetadata *ackv1alpha1.ResourceMetadata `json:"ackResourceMetadata"`
	// All CRs managed by ACK have a common `Status.Conditions` member that
	// contains a collection of `ackv1alpha1.Condition` objects that describe
	// the various terminal states of the CR and its backend AWS service API
	// resource
	// +kubebuilder:validation:Optional
	Conditions []*ackv1alpha1.Condition `json:"conditions"`
	// The creation time.
	// +kubebuilder:validation:Optional
	CreationTime *metav1.Time `json:"creationTime,omitempty"`
	// The ID of the Amazon Web Services account that owns the transit gateway.
	// +kubebuilder:validation:Optional
	OwnerID *string `json:"ownerID,omitempty"`
	// The state of the transit gateway.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty"`
	// The ID of the transit gateway.
	// +kubebuilder:validation:Optional
	TransitGatewayID *string `json:"transitGatewayID,omitempty"`
}

// TransitGateway is the Schema for the TransitGateways API
// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:printcolumn:name="ID",type=string,priority=0,JSONPath=`.status.transitGatewayID`
// +kubebuilder:printcolumn:name="state",type=string,priority=0,JSONPath=`.status.state`
type TransitGateway struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec   TransitGatewaySpec   `json:"spec,omitempty"`
	Status TransitGatewayStatus `json:"status,omitempty"`
}

// TransitGatewayList contains a list of TransitGateway
// +kubebuilder:object:root=true
type TransitGatewayList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items []TransitGateway `json:"items"`
}

func init() {
	SchemeBuilder.Register(&TransitGateway{}, &TransitGatewayList{})
}